on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test crane action
    steps:
      - uses: actions/checkout@v4
      - id: crane-setup
        uses: comdotlinux/crane@v0.0.7
        with:
          version: 'latest'
      - run: ${{ env.CRANE }} --help
        shell: bash
        env:
          CRANE: ${{ steps.crane-setup.outputs.crane }}